from io import BytesIO
from unittest import main, TestCase

from jd4._compare import compare_stream

def compare(a, b):
    return compare_stream(BytesIO(a), BytesIO(b))

class CompareTest(TestCase):
    def test_small(self):
        self.assertTrue(compare(b'', b''))
        self.assertTrue(compare(b'1 2 3', b'1 2 3'))
        self.assertTrue(compare(b'nana', b'nana'))
        self.assertFalse(compare(b'na', b'nana'))
        self.assertFalse(compare(b'nana', b'banana'))

        self.assertTrue(compare(b'', b' '))
        self.assertTrue(compare(b'', b'\n'))
        self.assertTrue(compare(b'', b'\n '))
        self.assertTrue(compare(b'', b' \n'))
        self.assertTrue(compare(b' ', b'\n'))
        self.assertTrue(compare(b'1\t2', b'1 2'))
        self.assertTrue(compare(b'1\n\n2', b'1\n2'))
        self.assertTrue(compare(b'1 \n2', b'1\n2'))
        self.assertTrue(compare(b'1\n 2', b'1\n2'))
        self.assertTrue(compare(b'1 2\t\t3', b'1 2 3'))
        self.assertTrue(compare(b'1 2 3', b'1\t2   3'))
        self.assertFalse(compare(b'1 23', b'1 2 3'))
        self.assertTrue(compare(b'line1  \nline2', b'line1\nline2'))

        self.assertTrue(compare(b'1 2 3\r\n', b'1 2 3\n'))
        self.assertTrue(compare(b'line1\r\nline2', b'line1\nline2'))
        self.assertFalse(compare(b'line1\rline2', b'line1\nline2'))
        self.assertFalse(compare(b'line1\r\nline2', b'line1\rline2'))
        self.assertFalse(compare(b'line1\r\r\nline2', b'line1\rline2'))

        self.assertTrue(compare(b'1\n', b'1'))
        self.assertTrue(compare(b'1 ', b'1'))
        self.assertTrue(compare(b'1\t', b'1'))
        self.assertTrue(compare(b'1\n ', b'1 \n'))
        self.assertTrue(compare(b'  1 2 3', b'1 2 3'))
        self.assertTrue(compare(b'\n\n1 2 3', b'1 2 3'))
        self.assertTrue(compare(b'\n \n1 2 3', b'1 2 3'))
        self.assertTrue(compare(b'1 2 3\n\n  \n', b'1 2 3'))

        self.assertFalse(compare(b'', b'1'))
        self.assertFalse(compare(b'1', b'2'))
        self.assertFalse(compare(b'1', b'1 2'))
        self.assertFalse(compare(b'1 2', b'12'))
        self.assertFalse(compare(b'1 2 3', b'1 2 4'))
        self.assertFalse(compare(b'1 2', b'1\n2'))
        self.assertFalse(compare(b'1  2', b'1\n 2'))
        self.assertFalse(compare(b'1  2', b'1 \n2'))
        self.assertFalse(compare(b'1  2', b'1\t\n 2'))

    def test_a_plus_b(self):
        answer = b'1 2\r\n'
        self.assertTrue(compare(answer, b'1 2'))
        self.assertTrue(compare(answer, b'1 2\n'))
        self.assertTrue(compare(answer, b'1 2\r'))
        self.assertTrue(compare(answer, b'1 2\r\n'))
        self.assertTrue(compare(answer, b'1 2 '))
        self.assertTrue(compare(answer, b'1 2 \n'))
        self.assertTrue(compare(answer, b'1 2 \r'))
        self.assertTrue(compare(answer, b'1 2 \r\n'))
        self.assertTrue(compare(answer, b'1  2'))
        self.assertTrue(compare(answer, b'1  2\n'))
        self.assertTrue(compare(answer, b'1  2\r'))
        self.assertTrue(compare(answer, b'1  2\r\n'))
        self.assertTrue(compare(answer, b'1  2 '))
        self.assertTrue(compare(answer, b'1  2 \n'))
        self.assertTrue(compare(answer, b'1  2 \r'))
        self.assertTrue(compare(answer, b'1  2 \r\n'))
        self.assertTrue(compare(answer, b' 1 2'))
        self.assertTrue(compare(answer, b' 1 2\n'))
        self.assertTrue(compare(answer, b' 1 2\r'))
        self.assertTrue(compare(answer, b' 1 2\r\n'))
        self.assertTrue(compare(answer, b' 1 2 '))
        self.assertTrue(compare(answer, b' 1 2 \n'))
        self.assertTrue(compare(answer, b' 1 2 \r'))
        self.assertTrue(compare(answer, b' 1 2 \r\n'))
        self.assertFalse(compare(answer, b'1 1'))
        self.assertFalse(compare(answer, b'1 1\n'))
        self.assertFalse(compare(answer, b'1 1\r'))
        self.assertFalse(compare(answer, b'1 1\r\n'))
        self.assertFalse(compare(answer, b'1 1 '))
        self.assertFalse(compare(answer, b'1 1 \n'))
        self.assertFalse(compare(answer, b'1 1 \r'))
        self.assertFalse(compare(answer, b'1 1 \r\n'))
        self.assertFalse(compare(answer, b' 1 1'))
        self.assertFalse(compare(answer, b' 1 1\n'))
        self.assertFalse(compare(answer, b' 1 1\r'))
        self.assertFalse(compare(answer, b' 1 1\r\n'))
        self.assertFalse(compare(answer, b' 1 1 '))
        self.assertFalse(compare(answer, b' 1 1 \n'))
        self.assertFalse(compare(answer, b' 1 1 \r'))
        self.assertFalse(compare(answer, b' 1 1 \r\n'))
        self.assertFalse(compare(answer, b'2 2'))
        self.assertFalse(compare(answer, b'2 2\n'))
        self.assertFalse(compare(answer, b'2 2\r'))
        self.assertFalse(compare(answer, b'2 2\r\n'))
        self.assertFalse(compare(answer, b'2 2 '))
        self.assertFalse(compare(answer, b'2 2 \n'))
        self.assertFalse(compare(answer, b'2 2 \r'))
        self.assertFalse(compare(answer, b'2 2 \r\n'))
        self.assertFalse(compare(answer, b' 2 2'))
        self.assertFalse(compare(answer, b' 2 2\n'))
        self.assertFalse(compare(answer, b' 2 2\r'))
        self.assertFalse(compare(answer, b' 2 2\r\n'))
        self.assertFalse(compare(answer, b' 2 2 '))
        self.assertFalse(compare(answer, b' 2 2 \n'))
        self.assertFalse(compare(answer, b' 2 2 \r'))
        self.assertFalse(compare(answer, b' 2 2 \r\n'))
        self.assertFalse(compare(answer, b'2 1'))
        self.assertFalse(compare(answer, b'2 1\n'))
        self.assertFalse(compare(answer, b'2 1\r'))
        self.assertFalse(compare(answer, b'2 1\r\n'))
        self.assertFalse(compare(answer, b'2 1 '))
        self.assertFalse(compare(answer, b'2 1 \n'))
        self.assertFalse(compare(answer, b'2 1 \r'))
        self.assertFalse(compare(answer, b'2 1 \r\n'))
        self.assertFalse(compare(answer, b' 2 1'))
        self.assertFalse(compare(answer, b' 2 1\n'))
        self.assertFalse(compare(answer, b' 2 1\r'))
        self.assertFalse(compare(answer, b' 2 1\r\n'))
        self.assertFalse(compare(answer, b' 2 1 '))
        self.assertFalse(compare(answer, b' 2 1 \n'))
        self.assertFalse(compare(answer, b' 2 1 \r'))
        self.assertFalse(compare(answer, b' 2 1 \r\n'))
        self.assertFalse(compare(answer, b'12'))

    def test_large(self):
        self.assertTrue(compare(b'a' * 1048576, b'a' * 1048576))
        self.assertFalse(compare(b'a' * 1048576, b'a' * 1048575 + b'b'))
        self.assertTrue(compare(b'a' * 1048576 + b' ' + b'b' * 1048576 + b'\r\n',
                                b'a' * 1048576 + b' ' * 1048576 + b'b' * 1048576))

if __name__ == '__main__':
    main()
